ci: debug

diff --git a/.github/workflows/sonar-cloud-static-code-analysis.yml b/.github/workflows/sonar-cloud-static-code-analysis.yml
--- a/.github/workflows/sonar-cloud-static-code-analysis.yml
+++ b/.github/workflows/sonar-cloud-static-code-analysis.yml
@@ -43,8 +43,7 @@ jobs:
       - name: Verify Directory Structure
         run: |
           echo "Current directory: $(pwd)"
-          echo "Project base directory: news-app"
-          ls -R news-app || echo "Directory not found"
+          ls -R /home/runner/work/news-app || echo "Directory not found"
 
       - name: Analyze with SonarCloud
         uses: sonarsource/sonarcloud-github-action@master
