ci: add more debugging logs

diff --git a/.github/workflows/sonar-cloud-static-code-analysis.yml b/.github/workflows/sonar-cloud-static-code-analysis.yml
--- a/.github/workflows/sonar-cloud-static-code-analysis.yml
+++ b/.github/workflows/sonar-cloud-static-code-analysis.yml
@@ -26,9 +26,6 @@ on:
 jobs:
   static-code-analysis:
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./${{ inputs.project_base_directory }}
 
     steps:
       - uses: actions/checkout@v4
@@ -43,8 +40,11 @@ jobs:
       - name: Setup SonarCloud
         uses: warchant/setup-sonar-scanner@v8
 
-      - name: Debug workspace
-        run: ls -R /home/runner/work || echo "Directory not found"
+      - name: Verify Directory Structure
+        run: |
+          echo "Current directory: $(pwd)"
+          echo "Project base directory: ${{ inputs.project_base_directory }}"
+          ls -R ${{ inputs.project_base_directory }} || echo "Directory not found"
 
       - name: Analyze with SonarCloud
         uses: sonarsource/sonarcloud-github-action@master
