ci: debug workspace

diff --git a/.github/workflows/sonar-cloud-static-code-analysis.yml b/.github/workflows/sonar-cloud-static-code-analysis.yml
--- a/.github/workflows/sonar-cloud-static-code-analysis.yml
+++ b/.github/workflows/sonar-cloud-static-code-analysis.yml
@@ -44,7 +44,7 @@ jobs:
         uses: warchant/setup-sonar-scanner@v8
 
       - name: Debug workspace
-        run: ls -R /home/runner/work/***/*** || echo "Directory not found"
+        run: ls -R /home/runner/work || echo "Directory not found"
 
       - name: Analyze with SonarCloud
         uses: sonarsource/sonarcloud-github-action@master
